### ISSUE TITLE
Initial Thoughts and Specifications

### ISSUE THREAD

**Issue by mehmetakiftutuncu** [mehmetakiftutuncu/Muezzin#1]
* API support will be API level 15 (Android 4.0.3) and above.
* Design should be following material design specifications.
* There should be reminders with a lot of customisations.
* There should be widget(s) with many sizes, themes and options.
* Overall resource usage should be minimum as there will be need for services for widgets and updating prayer times automatically.
* Automatic silence mode during prayer times

**Comment by EgyptianM** [comment]
good ideas 
waiting for the project :)

**Comment by mehmetakiftutuncu** [comment]
Today I'm releasing the first version with pretty much all the ideas above. The ones that are not implemented are mentioned in [README.md](https://github.com/mehmetakiftutuncu/Muezzin/blob/master/README.md).
