### ISSUE TITLE
i want to change prayer time and add some more city

### ISSUE THREAD

**Issue by abbehrang** [mehmetakiftutuncu/Muezzin#3]
i want to change prayer time and add some more city

# how ?

**Comment by mehmetakiftutuncu** [comment]
What exactly do you mean by changing prayer times and adding more cities?

**Comment by abbehrang** [comment]
my city not in list i want add my city to app and add prayer time for my city?

**Comment by mehmetakiftutuncu** [comment]
It is not possible to add a new city to Muezzin. It only serves data from Presidency of Religious Affairs website www.diyanet.gov.tr.

**Comment by abbehrang** [comment]
i want to change data and this site 

i want app just have my city time and i want type all of the address

**Comment by abbehrang** [comment]
can i set data from sqlite brose program 

please help me

**Comment by mehmetakiftutuncu** [comment]
Muezzin gets its data from https://github.com/mehmetakiftutuncu/MuezzinAPI. There's no other way to add data at the moment.

**Comment by abbehrang** [comment]
So what can I do?

**Comment by abbehrang** [comment]
can you help me step by step please

**Comment by mehmetakiftutuncu** [comment]
Feel free to fork the project and modify the code on your own. Or you can try other applications on Play Store. I don't have a plan for further development of Muezzin at the moment.

**Comment by abbehrang** [comment]
i want just shows my city time not show more city or countary 

thats good work for muslims people so plese help

**Comment by abbehrang** [comment]
i want add offline data from sqlite

**Comment by abbehrang** [comment]
can i make web site like this and run app on this site
https://muezzin-staging.herokuapp.com.

**Comment by mehmetakiftutuncu** [comment]
I already told you, there is no support for addition of data at the moment. If you can, modify the code on your own. If you can't, use some other application.

I'm closing the issue.

**Comment by abbehrang** [comment]
thanks
